defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: CI=false npm run build --if-present
    - name: List build directory
      run: ls -la ./build # List files in the build directory to verify output
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages
      - name: List downloaded artifact
        run: ls -la # List files to verify the artifact was downloaded correctly
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1